--splice-config=/usr/local/voiceanalysis/gplexva/model/splice.conf
--cmvn-config=/usr/local/voiceanalysis/gplexva/model/online_cmvn.conf
--lda-matrix=/usr/local/voiceanalysis/gplexva/model/final.mat
--global-cmvn-stats=/usr/local/voiceanalysis/gplexva/model/global_cmvn.stats
--diag-ubm=/usr/local/voiceanalysis/gplexva/model/final.dubm
--ivector-extractor=/usr/local/voiceanalysis/gplexva/model/final.ie
--num-gselect=5
--min-post=0.025
--posterior-scale=0.1
--max-remembered-frames=1000
--max-count=100
--ivector-period=10
--online-cmvn-iextractor=true
